### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by cmcnamara87** [cmcnamara87/progress-server-v4#1]
- [ ] add ability to delete projects
- [ ] single sign on (facebook)
- [ ] change 'journal' to 'projects'
- [ ] remove 'unfollow' button from everywhere expect profile page

**Comment by cmcnamara87** [comment]
Deleting directories
